export enum QuizReviewEvents {
  ON_REVIEW_START = "ON_REVIEW_START",
  ON_SUBMISSION_INITIATE = "ON_SUBMISSION_INITIATE",
  ON_SUBMISSION_CONFIRM = "ON_SUBMISSION_CONFIRM",
  ON_SUBMISSION_CANCEL = "ON_SUBMISSION_CANCEL",
  ON_QUESTION_SELECT = "ON_QUESTION_SELECT",
  ON_FILTER_CHANGE = "ON_FILTER_CHANGE",
}
