export enum SubmissionState {
  READY = "READY",
  REVIEW_REQUIRED = "REVIEW_REQUIRED",
  WARNING = "WARNING",
  BLOCKED = "BLOCKED",
  CONFIRMING = "CONFIRMING",
  SUBMITTING_PLACEHOLDER = "SUBMITTING_PLACEHOLDER",
}
