export enum QuizDeliveryCapabilities {
  SUPPORTS_SPLIT_LAYOUT = "SUPPORTS_SPLIT_LAYOUT",
  SUPPORTS_FULLSCREEN = "SUPPORTS_FULLSCREEN",
  SUPPORTS_STAGE_TRANSITIONS = "SUPPORTS_STAGE_TRANSITIONS",
}
